export const messageConstants = {
    SEND_REQUEST: 'SEND_REQUEST',
    SEND_SUCCESS: 'SEND_SUCCESS',
    SEND_FAILURE: 'SEND_FAILURE',
	
	GETSTATUS_REQUEST: 'GETSTATUS_REQUEST',
    GETSTATUS_SUCCESS: 'GETSTATUS_SUCCESS',
    GETSTATUS_FAILURE: 'GETSTATUS_FAILURE',
	
	ADD_MESSAGE: 'ADD_MESSAGE'
};